controller_manager:
  ros_parameters:
    update_rate: 30
    use_sim_time: true

    diff_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['Left_wheel_Joint']
    right_wheel_names: ['Right_wheel_Joint']
    wheel_separation: 0.35
    wheel_radius: 0.05

    use_stamped_vel: false
